import React, { useState } from 'react';
import { Recipe } from '../types';
import { Clock, BarChart, ChevronDown, ChevronUp, ShoppingBag } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface RecipeCardProps {
  recipe: Recipe;
}

export const RecipeCard: React.FC<RecipeCardProps> = ({ recipe }) => {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="bg-white rounded-xl shadow-md overflow-hidden border border-gray-100 transition-all hover:shadow-lg">
      <div className="p-5">
        <div className="flex justify-between items-start">
          <div>
            <h3 className="text-lg font-bold text-gray-800 leading-tight mb-1">{recipe.title}</h3>
            <p className="text-sm text-gray-500 line-clamp-2">{recipe.description}</p>
          </div>
          <span className={`px-2 py-1 rounded text-xs font-semibold whitespace-nowrap
            ${recipe.difficulty === 'Easy' ? 'bg-green-100 text-green-700' : 
              recipe.difficulty === 'Medium' ? 'bg-yellow-100 text-yellow-700' : 
              'bg-red-100 text-red-700'}`}>
            {recipe.difficulty}
          </span>
        </div>

        <div className="flex items-center gap-4 mt-4 text-xs text-gray-500">
          <span className="flex items-center gap-1"><Clock size={14} /> {recipe.cookingTime}</span>
          {recipe.calories && <span className="flex items-center gap-1"><BarChart size={14} /> ~{recipe.calories} kcal</span>}
        </div>

        {recipe.missingIngredients && recipe.missingIngredients.length > 0 && (
           <div className="mt-3 bg-red-50 p-2 rounded border border-red-100">
             <p className="text-xs font-bold text-red-700 flex items-center gap-1 mb-1">
               <ShoppingBag size={12} /> Missing Ingredients:
             </p>
             <p className="text-xs text-red-600">{recipe.missingIngredients.join(', ')}</p>
           </div>
        )}

        <button 
          onClick={() => setExpanded(!expanded)}
          className="w-full mt-4 flex items-center justify-center gap-1 text-sm text-indigo-600 font-medium py-2 hover:bg-indigo-50 rounded transition-colors"
        >
          {expanded ? 'Hide Recipe' : 'View Recipe'}
          {expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
        </button>
      </div>

      {expanded && (
        <div className="bg-gray-50 p-5 border-t border-gray-100 text-sm">
          <div className="mb-4">
            <h4 className="font-bold text-gray-700 mb-2">Instructions</h4>
            <ol className="list-decimal list-inside space-y-2 text-gray-600">
              {recipe.instructions.map((step, idx) => (
                <li key={idx} className="pl-1"><span className="ml-1">{step}</span></li>
              ))}
            </ol>
          </div>
          <div className="mt-4 pt-4 border-t border-gray-200">
            <p className="text-xs text-gray-400">
              Generated by Gemini 3 Flash. Always check food safety guidelines.
            </p>
          </div>
        </div>
      )}
    </div>
  );
};
